#!/bin/bash

# fogadja a feldolgozo geptol "vissza"-erkezo eredmenyeket

source base
source def

declare fName
#declare Nev
#declare Feladat
declare tSub

cd ${fromBack}

while true ; do

  for fName in $(find . -type f -printf "%f " ) ; 
  do
    tSub=${sub}"/list_"

    echo "${fName}" > ${tSub}
    cat ${sub}"/list" >> ${tSub}
    mv ${tSub} ${sub}"/list"

    rm -f ${fName}
  done

  sleep 2

done
