#!/bin/bash

# fogadja a feldolgozo geptol "vissza"-erkezo eredmenyeket

source base
source def

declare fName
#declare Nev
#declare Feladat
declare tSub

cd ${fbD}

while true ; do

  for fName in $(find . -type f -printf "%f " ) ; 
  do

#		Feladat=$( echo ${_F} | cut -d'_' -f 4 )
    tSub=${subList}"_"

    echo "${fName}" > ${tSub}
    cat ${subList} >> ${tSub}
    mv ${tSub} ${subList}

#		Nev=$(echo ${_F} | cut -d'_' -f 2 )
#		echo "${_F}" > ${CelKvt}/_eredmeny
# cat ${CelKvt}/ember/eredmeny >> ${CelKvt}/ember/_eredmeny
# mv ${CelKvt}/ember/_eredmeny ${CelKvt}/ember/eredmeny
    rm -f ${fName}

  done

  sleep 2

done
