#!/bin/bash

# fogadja a feldolgozo geptol "vissza"-erkezo eredmenyeket

source def.sh

declare fName
declare tSub

cd ${fromBack}

while true
do

  for fName in $( find . -name "*_res" -printf "%f " )
  do
    cp ${fName} ${base}"/sub/res"
    (
      source ${fName}
      row=${subId}"_"${userName}"_"${problemName}"_"${langName}"_"${all_ms}"_"${verdict}
      tSub=${base}"/sub/list"
      echo ${row} > ${tSub}"_"
      cat ${tSub} >> ${tSub}"_"
      mv ${tSub}"_" ${tSub}

      row=${subId}"_"${userName}"_"${langName}"_"${all_ms}"_"${verdict}
      tSub=${base}"/sub/problem/"${problemId}"/list"
      echo ${row} > ${tSub}"_"
      cat ${tSub} >> ${tSub}"_"
      mv ${tSub}"_" ${tSub}

      row=${subId}"_"${problemName}"_"${langName}"_"${all_ms}"_"${verdict}
      tSub=${base}"/sub/user/"${userId}"/list"
      echo ${row} > ${tSub}"_"
      cat ${tSub} >> ${tSub}"_"
      mv ${tSub}"_" ${tSub}

      rm -f ${base}"/lock/"${userId}_${problemId}
    )
    xCode=$?
    if (( xCode==0 ))
    then
      rm -f ${fName}
    fi

  done

  sleep 2

done
