#!/bin/bash

# fogadja a feldolgozo geptol "vissza"-erkezo eredmenyeket

source workRc

declare fName
declare tSub

cd ${fromBack}

while true
do

  for fName in $( find . -name "*_res" -printf "%f " )
  do
    cp ${fName} ${base}"/sub/res"
    (
      source ${fName}
      row=${subId}"_"${userName}"_"${problemName}"_"${langName}"_"${verdict}
      tSub=${base}"/sub/list"
      echo ${row} > ${tSub}"_"
      cat ${tSub} >> ${tSub}"_"
      mv ${tSub}"_" ${tSub}

      row=${subId}"_"${userName}"_"${langName}"_"${verdict}
      tSub=${base}"/problem/"${problemId}"/sub/list"
      echo ${row} > ${tSub}"_"
      cat ${tSub} >> ${tSub}"_"
      mv ${tSub}"_" ${tSub}

    )
    if [ $? = 0 ]
    then
      rm -f ${fName}
    fi

  done

  sleep 2

done
