#!/bin/bash

# atkuldi a feltoltott "oda" ahova kell

source workRc

cd ${work}"/toBack"

declare fName

while true ; do

  for fName in $(find . -name "*_src" -printf "%f " ) ; 
  do
# count uname problem lang
    (
      source ${subId}"_data"
      touch ${base}"/lock/"${userId}"_"${problemId}
    )
    subId=$(echo ${fName}|cut -d'_' -f1)
    tar cf ${subId}_pre  ${subId}_src ${subId}_data
    cp ${subId}_pre ${sub}"/pre"
    ${cpMethod} ${subId}_pre ${target}/${subId}_pre
    if [ $? = 0 ]
    then
      rm -f ${subId}_pre ${subId}_src ${subId}_data
    fi
  done
  sleep 2

done
