<?php
  $gMagam="prog";
  $gMsg="";
  $gColl=array(array("inc","null.php"));
  $gUname="";
  $gUid=-1;
  $gNevek=array(
    "info"=>"információ",
    "beg"=>"feladatok",
    "lout"=>""
  );
  $listFile="";
  $gSrcMaxSize=32768;
?>
