#!/bin/bash

source base
source def

declare fName
declare pName

# fromFront Dir
cd ${fromFront}

while true ;
do
  # sorszam ember feladat nyelv ido 
  for fName in $(find . -type f -printf "%f " )
  do
    pName=$(echo ${fName} | cut -d'_' -f 3)
    rm -f ${testBed}"/"*

    cp -L ${fName} ${work}"/tester" ${problem}"/"${pName}"/checker" ${work}"/base" ${work}"/def" ${testBed}

    ./tester ${fName}

    rm -f ${fName}
  done

  sleep 2

done
