#!/bin/bash

source workRc

cd ${work}

while true
do
  for tarF in $( find  "fromFront/" -name "*_pre" )
  do
    pre
    if [ ${verdict} = "_" ]
    then
      compile
    fi
    if [ ${verdict} = "_" ]
    then
      run
    fi
    post
  done
  sleep 2
done
