#!/bin/bash

source workRc

cd ${work}
while true
do
  for tarF in $( find  "fromFront/" -name "*_pre" )
  do
    
    pre; cd ${work}
    if [ ${verdict} = "_" ]
    then
      compile; cd ${work}
    fi
    if [ ${verdict} = "_" ]
    then
      run; cd ${work}
    fi
    post; cd ${work}
  done
  sleep 2
done
