#!/bin/bash

source def.sh
source work.sh

cd ${work}
while true
do
  for tarF in $( find fromFront/ -name "*_pre" -printf "%f " )
  do
    pre; cd ${work}
    if [ ${verdict} = "_" ]
    then
      compile; cd ${work}
    fi
    if [ ${verdict} = "_" ]
    then
      run; cd ${work}
    fi
    post; cd ${work}
  done
  sleep 2
done
