#!/bin/bash

# a kesz ures fajlokat visszajuttatja webszerverre

source base
source def

declare fName

cd ${work}"/toFront"

while true ;
do
  for fName in $(find "*_res" -type f -printf "%f " ) ; 
  do
    ${cpMethod} ${fName} ${targetDir}
    rm -f ${fName}
  done
  sleep 2
done
