#!/bin/bash

# a kesz ures fajlokat visszajuttatja webszerverre

source def.sh

declare fName

declare -r target=${front}"/work/fromBack"
cd ${work}"/toFront"

while true
do
  for fName in $(find . -name "*_res" -printf "%f " )
  do
    ${cpMethod} ${fName} ${target}
    if [ $? = 0 ]
    then
      rm -f ${fName}
    fi
  done
  sleep 2
done
